### ISSUE TITLE
Bug in test suite?

### ISSUE THREAD

**Issue by gwerbin** [luarocks/hererocks#25]
The test `TestCLI.test_verbose_install_bleeding_edge_luajit_with_latest_luarocks` is failing with the following output mismatch:

```none
E                   AssertionError: Expected to see 'b'LuaJIT 2.1.0'' in output of command 'test/here/bin/lua -v', got output:
E                   b'LuaJIT 2.1.ROLLING -- Copyright (C) 2005-2023 Mike Pall. https://luajit.org/\n'
```

This seems like an unintentional failure. As far as I can tell, the test is succeeding: Hererocks is correctly installing the requested version, and the `lua` command appears to be running the correct program. It seems like this `assertSuccess` method needs to be adapted somehow to accommodate a prefix match, or the output from `lua -v` needs to be truncated.

**Comment by un-def** [comment]
Good catch! 

LuaJIT recently switched to the rolling release scheme:

* 2.0.x -> 2.0.ROLLING
* 2.1.x -> 2.1.ROLLING

See LuaJIT commits:

* 50e0fa03c48cb9af03c3efdc3100f12687651a2e
* 2090842410e0ba6f81fad310a77bf5432488249a

A fix is on the way.

**Comment by gwerbin** [comment]
Thanks! It's worth noting that this actually broke installation from AUR with Yay, because the Arch packaging tools run the test suite by default.

For anyone reading this between now and when the fix is released:

```bash
yay -S --mflags --nocheck hererocks
```
