### ISSUE TITLE
macos error: Makefile:319: *** missing: export MACOSX_DEPLOYMENT_TARGET=XX.YY.  Stop.

### ISSUE THREAD

**Issue by tenturestept** [luarocks/hererocks#31]
an error when building luajit:

```
python3 ~/Downloads/hererocks.py --verbose test --compat none -j @v2.1 --patch -r latest
Cloning LuaJIT from https://github.com/LuaJIT/LuaJIT @v2.1 (cached)
Running git rev-parse --quiet --verify v2.1
d06beb0480c5d1eb53b3343e78063950275aa281
Running git checkout v2.1
Already on 'v2.1'
Your branch is up to date with 'origin/v2.1'.
Running git symbolic-ref -q HEAD
refs/heads/v2.1
Running git pull --rebase
Already up to date.
Running git rev-parse HEAD
d06beb0480c5d1eb53b3343e78063950275aa281
Building LuaJIT @d06beb0
Running make
==== Building LuaJIT 2.1 ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
Makefile:319: *** missing: export MACOSX_DEPLOYMENT_TARGET=XX.YY.  Stop.
make: *** [default] Error 2
Error: got exitcode 2 from command make
```

**Comment by hishamhm** [comment]
> Makefile:319: *** missing: export MACOSX_DEPLOYMENT_TARGET=XX.YY.  Stop.

try running the command `export MACOSX_DEPLOYMENT_TARGET=XX.YY` for your `XX.YY` version of macOS first?

**Comment by un-def** [comment]
This is not related to rolling release changes, this env variable has always been required. On CI I used some artibrary value: https://github.com/luarocks/hererocks/blob/c5f78495359f766bea2ca6f7ca5bcc74a4108447/.github/workflows/test.yml#L40

I think we can do the following:

* if `MACOSX_DEPLOYMENT_TARGET` — do nothing
* if `MACOSX_DEPLOYMENT_TARGET` is not set — set it to the the running version

I don't have a macOS device at hand, I'll check later and make a PR.

**Comment by un-def** [comment]
Is this LuaJIT-specific, or PUC-Rio Lua requires `MACOSX_DEPLOYMENT_TARGET` as well?

**Comment by un-def** [comment]
@tenturestept could you check again with a fresh copy of hererocks.py, please? The variable is set automatically now, you don't need to `export MACOSX_DEPLOYMENT_TARGET=XX.YY` anymore.
